services:
    # Error Manager
#    peary.exception_listener:
#        class: Vted\PearyBundle\Listener\ExceptionListener
#        arguments: ['@service_container']
#        tags:
#            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }